services:
  playwright:
    image: playwright-test
    build: 
      context: .
      dockerfile: ./Dockerfile
    command: npm run test:docker
    volumes:
      - ./playwright-report:/app/playwright-report
      - ./test-results:/app/test-results
      - ./allure-results:/app/allure-results
    